# Generated by Django 5.0 on 2023-12-13 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tiendasSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=40, null=True)),
                ('region', models.CharField(blank=True, max_length=40, null=True)),
                ('fechaCreacion', models.DateField(blank=True, max_length=40, null=True)),
                ('telefonoContacto', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='productosSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=60, null=True)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('precio', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad', models.CharField(blank=True, max_length=20, null=True)),
                ('tiendaProducto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionTienda.tiendassistema')),
            ],
        ),
    ]
